### ISSUE TITLE
Commas instead dots

### ISSUE THREAD

**Issue by SimonBourdareau** [gifford-lab/GEM3#2]
Dear GEM3 developer,

I'm facing a problem with KMAC and KSM. It seems that KMAC generates KSM motifs with commas instead of dots for:
- the fourth row of the header
- the values in column HgpLg10
- the values list at the end of the file

When I try to run KSM on a KMAC output
`java -jar ~/gem/gem.jar KSM --fasta ES_Oct4_61bp.fasta --ksm Oct4.ksm_list.txt --out Oct4.KSM.scan`

java returns the following error:

> Exception in thread "main" java.lang.NumberFormatException: For input string: "3,10"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1250)
	at java.lang.Double.parseDouble(Double.java:540)
	at edu.mit.csail.cgs.deepseq.discovery.kmer.GappedKmer.loadKSM(GappedKmer.java:313)
	at edu.mit.csail.cgs.deepseq.discovery.kmer.GappedKmer.loadKSM(GappedKmer.java:270)
	at edu.mit.csail.cgs.deepseq.utilities.CommonUtils.loadKsmFile(CommonUtils.java:800)
	at edu.mit.csail.cgs.deepseq.analysis.MotifScan.findMotifInstances(MotifScan.java:180)
	at edu.mit.csail.cgs.deepseq.analysis.MotifScan.main(MotifScan.java:32)
	at edu.mit.csail.cgs.deepseq.discovery.GEM.main(GEM.java:315)

This is true for both Java 1.7 and 1.8.

Here, the first lines of the KSM m0:

> #Oct4.m0
#KSM version: 1
#5000/5000
#3,10
#k-mer/r.c.    	Offset	PosCt	wPosCt	NegCt	HgpLg10	CIDs	PosHits (base85 encoding)	NegHits (base85 encoding)
ATGCAAA/TTTGCAT	1	529	529	61	-113,4	*	"9Ouf2^CY>4An'M.q7d0`..h4N!)?Fl&QU1%L2uE?i^;'&VL8q!('/**(g>>"9<rP,m+/^$j&[J!!!R-!XM%VTRafXYQ+ZV!*fXP&-/J5!'h8*"Ft.e^]4?G!!=VL"<_(P#m^MI!YSodJ3a/E!<<\)!!!!a!!!Q1!._ibJIMm8!!!!1JI2AW+@/Oq!!iW<"9\_?!!<3d+Ue>^!!!-%#ljr+5QhX[!/)JN!!!!a!$DPT!!:RK&cht46jNdc!!!!-!!"5DJcGiR![7UE!!u0r!0@53!5JR7QiROj!!E9E!<<*%TKiJ[J7JpB!'gYe!'gMaz#QOi)!!!$E!!#h,!!#gs!WW3#"9Lgg!.Y%L![7XF5QCcq!)NY"z!!!-%!<`H(!!E9%(]XO9!!!Q1!!iiE!!!-&&BFhOTE##n#QOi*!$G5@"A'^9!!*'*!#PeL!!!!"!.Y%L#QP,1!WW3#!/1E'!!!!Iz!$DmS!<E0#z#QOj5J,k*"!WX>C!!3-##QOo+Jj9;9!!!!1!'hZW!"csH%MJgF!!!$"&-)\1+96p'!!!!#'EAsM+:&5Q(dJ(Q+92ZI#XAA4!!#OkJ,fS2z63%&u!!3-#!!!''!'gMa!0@0\!!3-#J,oWMJ.R52z!!!"L#QOjTJ-5iP0E?V'!!3-#!!!!%!!!"Lz!.Y%L!!!!A!$D7B!!!!)!"^7Q!<Q't!!!!A!.Y%L!13`dz!!%NM!!!!"!!"-,!!!!1&:a`\!<@cQz#Q~	zz!"],A!!!-%!!E9&z!!!!%!!!"Lz!!E9%zz!!!!#z!!Ei5zJ,fQLzz!!!!a!"],1zz!!39'zzz!!#7az!<<*"!!!!bzzzz"9Ac.!!!9)z!!!Q1z"98EEzzzzzzz!!!'#!!!'#z!!!-%zz!!!'#!!!$"!!!!A!!!9)z!!!!"!'gMazz!!iRTzzzzzz!!!!%zzz!!iQ)z!"],1zz#QOi)z!!!Q1z!!!!)zzzz#QTATzzzzz!!!!#zz!!!!"zzzzz&-)\3#QOi)!$D7Azzzzzzzzzzz!!!9)!!!!1zzzzzzzzzzz!!!$"zzzzz!!!-%zzzzz#QOi)zzzzz!.Y(Mz!!!!#!!!!a~
ATGCNAAT/ATTNGCAT	1	433	467	19	-118,5	0,-1	N.A.	N.A.
ATGCANAT/ATNTGCAT	1	402	444	19	-111,5	0,2	N.A.	N.A.
TATGCANA/TNTGCATA	0	367	408	26	-93,5	-3,4,5	N.A.	N.A.
ATGNAAAT/ATTTNCAT	1	372	401	15	-103,0	6,0	N.A.	N.A.

Moreover, I  was wondering if it could be possible to save the aligned sequences (with N) that appear in the 'Aligned bound sequences' heatmap in an additional text file.

Otherwise, KMAC is one of the most convincing motif discovery software. I really appreciate that it is able to identify motifs so quickly on ChIP-seq/DAP-seq/Genome data.
Best,
Simon

**Comment by yguoma** [comment]
Hi Simon,

This is a strange effect that I have not seen before. Are you running KMAC
on a non-English operating system?

If you add a --print_aligned_seqs flag, you can print out the sequences
aligned by the KSMs.

Best,

Yuchun

**Comment by SimonBourdareau** [comment]
Hi Yuchun,

This is very unusual as I already use Java-encoded programs and never face this kind of errors but I finally solved it. Indeed, my OS is a Ubuntu distribution with the language set in French. I changed for English and obtain a KMAC output with dots working with KSM.

Thanks a lot,

Best,
Simon

**Comment by H1889** [comment]
I have solved the problem of decimals. Despite my system uses decimals with ".", GEM runs with  Java that does not use the system configurtion, Java uses the language configuration, so I changed my language to american english and the problem was solved.
Sorry for the inconvenience.
Best
